services:
  db:
    image: postgres:15.2
    container_name: polar-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - polar-network
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

  catalog-service:
    image: catalog-service:latest
    container_name: polar-catalog-service
    #restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/polardb_catalog
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - polar-network

  order-service:
    image: order-service:0.0.1-SNAPSHOT
    container_name: polar-order-service
    #restart: always
    environment:
      SPRING_FLYWAY_URL: jdbc:postgresql://db:5432/polardb_order
      SPRING_R2DBC_URL: r2dbc:postgresql://db:5432/polardb_order
      POLAR_CATALOG_SERVICE_URI: http://catalog-service:8080
      RABBIT_URI: polar-rabbitmq
    depends_on:
      - db
      - catalog-service
      - polar-rabbitmq
    ports:
      - 8090:8090
    networks:
      - polar-network

  edge-service:
    image: edge-service:0.0.1-SNAPSHOT
    container_name: polar-edge-service
    #restart: always
    environment:
      ORDER_SERVICE_URI: http://order-service:8090
      CATALOG_SERVICE_URI: http://catalog-service:8080
      REDIS_URI: polar-redis
    depends_on:
        - order-service
        - catalog-service
        - polar-redis
    ports:
        - 9200:9200
    networks:
        - polar-network

  dispatcher-service:
    image: dispatcher-service:0.0.1-SNAPSHOT
    depends_on:
      - polar-rabbitmq
    container_name: polar-dispatcher-service
    environment:
      RABBIT_URI: polar-rabbitmq
    ports:
      - 9003:9003
    networks:
        - polar-network

  polar-redis:
    image: redis:7.2-rc1
    container_name: polar-redis
    restart: always
    ports:
      - 6379:6379
    networks:
        - polar-network

  polar-rabbitmq:
    image: rabbitmq:3.10.22-management
    container_name: polar-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
        - polar-network
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  polar-keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: polar-keycloak
    ports:
      - 8080:8080
    command: start-dev --import-realm
    volumes:
      - ./keycloak/:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
    networks:
      - polar-network


# this container is for debugging purposes only
#  ubuntu-curl:
#    image: ubuntu:22.04
#    container_name: ubuntu-curl
#    command: sleep infinity
#    tty: true
#    stdin_open: true
#    networks:
#      - polar-network


networks:
  polar-network:
    driver: bridge